### ISSUE TITLE
Visible tool is not the real active tool after game ends

### ISSUE THREAD

**Issue by Harfeur** [lucasnlm/antimine-android#432]
**Describe the bug**
When you end a game and you choose to restart a new game, if you click on a tile, the bomb is revealed even if the default tool was the flag.

**To Reproduce**
End a game, click new game, click on tiles

**What control style do you use?**
Button to switch between Flag and Open

**Expected behavior**
Place a flag on the tile

**Screenshots**
https://user-images.githubusercontent.com/22135449/234014816-ddd57b85-9db7-4b59-9d94-ac4218e9ada1.mp4

**Android Version:**
CalyxOS 4.8.1 (Android 13)

**App Version**
17.2.1 F

**Comment by lucasnlm** [comment]
Hi!
Thanks for your bug report.
I think this bug was fixed on `17.2.2` (https://github.com/lucasnlm/antimine-android/releases/tag/17.2.2). You are on `17.2.1`.
Can you check on this version, please?

**Comment by Astoralis** [comment]
I just wanted to report the same bug, then I saw the message, updated the game but the error still persists. 
Love your work btw

**Comment by lucasnlm** [comment]
I think I found another possible root cause. It hope `17.2.3` fixes this bug.

**Comment by Harfeur** [comment]
Fixed with 17.2.3 ! Thank you !
