### ISSUE TITLE
F-Droid build failed

### ISSUE THREAD

**Issue by linsui** [lucasnlm/antimine-android#470]
https://monitor.f-droid.org/builds/log/dev.lucanlm.antimine/1705061#site-footer Could you please take a look? Thanks!

**Comment by lucasnlm** [comment]
@linsui I just released a new version. I hope it fixes the build.

**Comment by linsui** [comment]
https://gitlab.com/linsui/fdroiddata/-/jobs/5464389590 The build still fails.

**Comment by licaon-kter** [comment]
and again https://gitlab.com/fdroid/fdroiddata/-/jobs/5468271156#L1516

**Comment by lucasnlm** [comment]
@linsui @licaon-kter Is there any way to reproduce the F-droid build script locally? It would be helpful.

**Comment by licaon-kter** [comment]
It's all there in the link above :)

```
rm -fr proprietary app/gradle
sdkmanager 'cmake;3.22.1'
sed -i -e "/:proprietary/d" ../settings.gradle build.gradle
sed -i -e '/gms/d' -e '/firebase/d' {.,..}/build.gradle
gradle clean
gradle assembleFossRelease
```

**Comment by lucasnlm** [comment]
@licaon-kter Please, can you please replace in the build script following line? 

```
sed -i -e '/gms/d' -e '/firebase/d' {.,..}/build.gradle
```

by:

```
sed -i -e '/bugsnag/d' -e '/gms/d' -e '/firebase/d' {.,..}/build.gradle
```

**Comment by licaon-kter** [comment]
```
> Task :app:mergeFossReleaseJavaResource

> Task :app:minifyFossReleaseWithR8
WARNING: /home/vagrant/build/dev.lucanlm.antimine/app/build/intermediates/merged_java_res/fossRelease/mergeFossReleaseJavaResource/base.jar: R8: Unexpected reference to missing service class: META-INF/services/javax.annotation.processing.Processor.
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/vagrant/build/dev.lucanlm.antimine/app/build/outputs/mapping/fossRelease/missing_rules.txt.
ERROR: R8: Missing class javax.annotation.processing.AbstractProcessor (referenced from: void com.google.auto.service.processor.AutoServiceProcessor.<init>() and 1 other context)
Missing class javax.annotation.processing.SupportedOptions (referenced from: com.google.auto.service.processor.AutoServiceProcessor)

> Task :app:minifyFossReleaseWithR8 FAILED
> Task :app:lintVitalAnalyzeFossRelease

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyFossReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete
```

**Comment by lucasnlm** [comment]
It was another error on my side.
I just released a new version to fix that.
With the `sed -i -e '/bugsnag/d' -e '/gms/d' -e '/firebase/d' {.,..}/build.gradle` change it should work now.

**Comment by linsui** [comment]
Fixed, thanks!

**Comment by licaon-kter** [comment]
Do reopen: https://gitlab.com/fdroid/fdroiddata/-/jobs/7281022527

**Comment by lucasnlm** [comment]
Thanks for letting me know. I bumped android SDK. I will fix.
